### ISSUE TITLE
json2gsc: executable not found

### ISSUE THREAD

**Issue by ghost** [cato-a/zzz_jumpmod#3]
Hi i was getting this error: `json2gsc: executable not found` but it was because i didn't have cmake installed when i tried at first, but the folder got created anyway, so i guess the script thought i had the required file

deleting the folder and executing the script again passed this error, now updating cmake

**Comment by raphael12333** [comment]
apparently it was because i didn't have cmake installed when i tried at first, but the folder got created anyway
deleting the folder and executing the script again passed this error, now i need to update cmake

**Comment by ghost** [comment]
then got this:

![Screenshot 2024-10-21 080855](https://github.com/user-attachments/assets/7fe6b338-8c8d-4b1f-aa31-ec6f1bc80183)

did `apt install build-essential` then got this:

![Screenshot 2024-10-21 081042](https://github.com/user-attachments/assets/a0bc61e4-bd1a-40fb-a53a-348a386c526a)

did `apt install zip` then got this:

![Screenshot 2024-10-21 081228](https://github.com/user-attachments/assets/83282b9f-bb36-460e-9ac1-f7b47ba04d97)

**Comment by ghost** [comment]
i don't know if you would prefer i close the issue or not so i leave it open
regards

**Comment by cato-a** [comment]
Hi, thanks for the info. I guess the script can be updated in the future with a check to see if `zip` and `cmake` is installed. Currently it just assumes you have those tools already installed.

**Comment by cato-a** [comment]
Updated the README with install instructions for required build tools, and compile script with additional checks.

https://github.com/cato-a/zzz_jumpmod/commit/50d584587ec53e35d5524fcba651b6252709daa5
https://github.com/cato-a/zzz_jumpmod/commit/c66e34d1058c427df3cbded967b5b807ab77168b
